[package]
name = "webhookntfy"
version = "0.1.0"
edition = "2021"
authors = ["martabal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.7"
tokio = { version = "1.25.0", features = ["full"] }
serde_json = "1.0"
serde_derive = "1.0.152"
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11.14"
dotenv = "0.15.0"
serde_yaml = "0.9"
